# Starter pipeline
- task: RunFromFileSystemTask@1
  inputs:
    testPathInput: 'C:\Users\mdalal\OneDrive - Schlumberger\PCAutomationFramework\PCDriverOld'

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    Settings
    - task: RunFromALM@1
    inputs:
    varAlmserv: 'https://saphpalm.itt.slb.com/qcbin/'
    varUserName: 'mdalal'
    varPass: 'Dec@2019mani'
    varDomain: 'ITT_SAP'
    varProject: 'ITT_SAP_Automation_TCoE'
    varTestsets: 'TESTVSTS'
  displayName: 'Run a multi-line script'
